language: ruby
rvm:
  - "1.9.2"
  - "2.0.0"

script: "./bin/wraith capture test_config"

notifications:
  email:
    recipients:
      - david.blooman@bbc.co.uk
    on_failure: change
    on_success: never
