base_domain: "http://google.co.uk"
compare_domain: "http://google.fr"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 768
  - 1024
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  search_page: imghp
  map_page: maps

output: "shots"
diff_threshold: 200
