# The name of the directory where shots will be saved/
directory:
  - 'afrique'

# Add only 2 domains, key will act as a label
domains:
  test: "http://m.live.bbc.co.uk/news"
  live: "http://www.live.bbc.co.uk/russian"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  # - 600
  # - 768
  # - 1024
  # - 1280

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  # videos: /liste_mots_cles/videos

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

