#Headless browser option
browser:
  webkit: "phantomjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/wraith/javascript/snap.js"

#Specify the engine that should be used to compare again the main engine
compare_browser:
  gecko: "slimerjs"

#If you want to have a different snapping files from the main snap file for the comparison engine set the file name here. This will fallback to the snap_file above if not specified
#compare_snap_file: "lib/wraith/javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots/compare/chrome_firefox'

# Add only 2 domains, key will act as a label
domains:
  english: "http://www.live.bbc.co.uk/news"

#Type screen widths below, here are a couple of examples
screen_widths:
 - 1024
 # - 320
 # - 600
 # - 768
 # - 1024
 # - 1280
 # - 1440
 # - 1960

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  #uk_index: /uk

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '60%'

#Set the number of days to keep the site spider file
spider_days:
  - 10
