#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

device:
  base: firefox
  compare: firefox

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/wraith/javascript/snap_meetup_mobile.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
  live: "http://www.meetup.com"
  dev: "http://www.dev.meetup.com"

# Cookies following PhantomJS format, via YAML.
cookies:
  - { name: "_mobile", value: "on", domain: ".meetup.com" }
  - { name: "__nodump", value: "true", domain: ".meetup.com" }

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 640

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  activity: /find/?activity=true

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10
