#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

##If you want to have multiple snapping files, set the file name here
snap_file: "javascript/snap_news.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'news'

domains:
 code: http://pal.stage.bbc.co.uk
 live: http://pal.live.bbc.co.uk

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 599
  - 600
  - 768
  - 1024
  # - 1280

#Type page URL paths below, here are a couple of examples
paths:
  front_page_news: /news
  story_page_news: /news/uk-politics-21271670
  live_page_news: /news/uk-politics-17456712
  story_page_news_hyper: /news/world-africa-21056884
  media_page_news: /news/uk-21163565
  # story_page_news_images: /news/uk-21112189
  gallery_page_news: /news/in-pictures-21828015
  gallery_picture: /news/in-pictures-21828015#1
  local_page_news: /news/england/london
  channel_page: /news/10318089
  correspondent: /news/correspondents/rorycellanjones
  correspondent_piece: /news/technology-23312579
  in_pictures_index: /news/in_pictures
  special_reports: /news/world-middle-east-17258397
  special_reports_index: /news/special_reports
  queens: /news/blogs/queens_baton_relay
  queens_story: /news/blogs-queens-baton-relay-24706292

fuzz: '20%'
  #Set the number of days to keep the site spider file
spider_days:
  - 10
